version: '3'
services:
  maven:
    image: maven:3-jdk-11
    command: $COMMAND
    volumes:
      - /etc/passwd:/etc/passwd
      - ${PWD}:/usr/src/mymaven
      - ~/.m2/repository:/var/maven/.m2/repository
      - ~/.m2/settings.xml:/var/maven/.m2/settings.xml
    working_dir: /usr/src/mymaven
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      MAVEN_OPTS: -Duser.home=/var/maven -Xmx512m
    user: $USERID:$GROUPID
