version: '3'
services:
  mongo:
    image: mongo:4.1
    command: --serviceExecutor adaptive
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
    - "27017:27017"
  mongo-express:
    image: mongo-express:0.54.0
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME : admin
      ME_CONFIG_MONGODB_ADMINPASSWORD : mongoadmin
      ME_CONFIG_BASICAUTH_USERNAME : admin
      ME_CONFIG_BASICAUTH_PASSWORD : admin
    ports:
      - "8089:8081"
    depends_on:
      - "mongo"
