version: '3'
services:
  mongo:
    image: mongo:4.1
    command: --serviceExecutor adaptive
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
    - "27017:27017"