version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: tagger-userdb
      POSTGRES_USER: postgresIdp
      POSTGRES_PASSWORD: postgres1
      PGDATA : /var/lib/postgresql/data/pgdata
